include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    sort_pub_dependencies: false
    avoid_web_libraries_in_flutter: false
    lines_longer_than_80_chars: false
    public_member_api_docs: false
